### ISSUE TITLE
Feature Request: Support for element screenshots

### ISSUE THREAD

**Issue by RyKilleen** [Visual-Regression-Tracker/agent-playwright#22]
Currently, Playwright supports taking element screenshots:

```
await page.goto('https://google.com', { waitUntil: 'domcontentloaded' })
const element = await page.$('[role="search"]')
await element.screenshot({...})```
```

Supporting the [ElementHandle](https://playwright.dev/#version=v1.0.2&path=docs%2Fapi.md&q=class-elementhandle) type upstream in the Playwright agent would be great!

**Comment by pashidlos** [comment]
released in `4.3.0`
