### ISSUE TITLE
Request: Default tolerance settings

### ISSUE THREAD

**Issue by RyKilleen** [Visual-Regression-Tracker/agent-playwright#56]
This may already be a thing, but I'm looking to globally configure tolerance settings for screenshots (either in the `vrt.json` or elsewhere.)

Is there any desire for a PR for something like that?

**Comment by pashidlos** [comment]
@RyKilleen thanks for the ticket!
yeah, I'm considering to add this kind of a global config
but not sure about `diffTollerance` in particular 
tbh I believe it should always stay in `0` 

could you elaborate the case when you need this kind of a setting?
